import {
  GiAlarmClock,
  GiArchiveResearch,
  GiLaptop,
  GiPoolTriangle,
} from "react-icons/gi";

export const CourseCategory = [
  {
    name: "Graphics Design",
    shortDescription:
      "Lorem Ipsum is simply for this dummy text of the printing.",
    totalCourse: 23,
    thumbnail: "/images/category-01.jpg",
  },
  {
    name: "Business Analysis",
    shortDescription:
      "Lorem Ipsum is simply for this dummy text of the printing.",
    totalCourse: 18,
    thumbnail: "/images/category-02.jpg",
  },
  {
    name: "Date Science",
    shortDescription:
      "Lorem Ipsum is simply for this dummy text of the printing.",
    totalCourse: 15,
    thumbnail: "/images/category-03.jpg",
  },
  {
    name: "Architecture",
    shortDescription:
      "Lorem Ipsum is simply for this dummy text of the printing.",
    totalCourse: 20,
    thumbnail: "/images/category-04.jpg",
  },
];

export const Courses = [
  {
    id: 1,
    title: "Competitive Strategy law for all students",
    author: {
      name: "James Carlson",
      profilePic: "/images/instructor-1.jpg",
      profilePicBig: "/images/About/instructor-1.jpg",
      degination: "SEO Expert",
      email: "James@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.6,
    totalReviw: 56,
    mainthumbnail: "/images/course-01.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 3, min: 14, sec: 20 },
    entrolled: 367,
    lecture: 29,
    skill: "Intermediate",
    language: "English",
    quiz: 12,
    certificate: "Yes",
    passParcentage: 80,
    deadline: "25 Dec, 2022",
    category: "Web Development",
    price: 45,
  },
  {
    id: 2,
    title: "Machine Learning A-Z: Hands-On Python and java",
    author: {
      name: "Nancy Phipps",
      profilePic: "/images/instructor-2.jpg",
      profilePicBig: "/images/About/instructor-2.jpg",
      degination: "Digital Marketer",
      email: "Nancy@example.com",
      phone: "806-740-0589",

      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.4,
    totalReviw: 25,
    mainthumbnail: "/images/course-02.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 8, min: 15, sec: 20 },
    entrolled: 255,
    lecture: 35,
    skill: "Advanced",
    language: "English",
    quiz: 10,
    certificate: "Yes",
    passParcentage: 90,
    deadline: "28 Dec, 2022",
    category: "Business",
    price: 55,
  },
  {
    id: 3,
    title: "Achieving Advanced in Insights with Big",
    author: {
      name: "Linda Bacote",
      profilePic: "/images/instructor-6.jpg",
      profilePicBig: "/images/About/instructor-6.jpg",
      degination: "PHP Expert",
      email: "Linda@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 3.6,
    totalReviw: 23,
    mainthumbnail: "/images/course-03.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 15, min: 35, sec: 18 },
    entrolled: 550,
    lecture: 40,
    skill: "Beginer",
    language: "English",
    quiz: 15,
    certificate: "Yes",
    passParcentage: 90,
    deadline: "30 Dec, 2022",
    category: "Education",
    price: 48,
  },
  {
    id: 4,
    title: "Education Makes A Person A Responsible Citizen",
    author: {
      name: "Alice McCoy",
      profilePic: "/images/instructor-8.jpg",
      profilePicBig: "/images/About/instructor-8.jpg",
      degination: "UI Designer",
      email: "Alice@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 3.4,
    totalReviw: 35,
    mainthumbnail: "/images/course-04.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 20, min: 15, sec: 10 },
    entrolled: 250,
    lecture: 55,
    skill: "Intermediate",
    language: "English",
    quiz: 25,
    certificate: "Yes",
    passParcentage: 80,
    deadline: "10 Dec, 2022",
    category: "Marketing",
    price: 89,
  },
  {
    id: 5,
    title: "Building A Better World One Student At A Time",
    author: {
      name: "James Carlson",
      profilePic: "/images/instructor-1.jpg",
      profilePicBig: "/images/About/instructor-1.jpg",
      degination: "Digital Marketer",
      email: "James@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 3,
    totalReviw: 19,
    mainthumbnail: "/images/course-05.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 15, min: 35, sec: 20 },
    entrolled: 243,
    lecture: 58,
    skill: "Beginer",
    language: "English",
    quiz: 14,
    certificate: "Yes",
    passParcentage: 80,
    deadline: "27 Dec, 2022",
    category: "Language Learning",
    price: "Free",
  },
  {
    id: 6,
    title: "Education is About Forming Faithful Disciples",
    author: {
      name: "Nancy Phipps",
      profilePic: "/images/instructor-2.jpg",
      profilePicBig: "/images/About/instructor-2.jpg",
      degination: "Digital Marketer",
      email: "Nancy@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.6,
    totalReviw: 20,
    mainthumbnail: "/images/course-06.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 26, min: 18, sec: 40 },
    entrolled: 360,
    lecture: 48,
    skill: "Advanced",
    language: "English",
    quiz: 15,
    certificate: "Yes",
    passParcentage: 90,
    deadline: "15 Dec, 2022",
    category: "Business",
    price: 19,
  },
  {
    id: 7,
    title: "Growing Together to Create Lifelong Learners",
    author: {
      name: "Linda Bacote",
      profilePic: "/images/instructor-6.jpg",
      profilePicBig: "/images/About/instructor-6.jpg",
      degination: "Digital Marketer",
      email: "Linda@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.6,
    totalReviw: 15,
    mainthumbnail: "/images/course-07.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 13, min: 38, sec: 50 },
    entrolled: 450,
    lecture: 85,
    skill: "Intermediate",
    language: "English",
    quiz: 19,
    certificate: "Yes",
    passParcentage: 80,
    deadline: "21 Dec, 2022",
    category: "Education",
    price: 59,
  },
  {
    id: 8,
    title: "Education is About Preparing Students for College",
    author: {
      name: "Alice McCoy",
      profilePic: "/images/instructor-8.jpg",
      profilePicBig: "/images/About/instructor-8.jpg",
      degination: "Digital Marketer",
      email: "Alice@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.6,
    totalReviw: 14,
    mainthumbnail: "/images/course-08.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 8, min: 14, sec: 55 },
    entrolled: 135,
    lecture: 35,
    skill: "Intermediate",
    language: "English",
    quiz: 11,
    certificate: "Yes",
    passParcentage: 90,
    deadline: "15 Nov, 2022",
    category: "Web Development",
    price: 35,
  },
  {
    id: 9,
    title: "Java Programming Masterclass for Software Developers",
    author: {
      name: "Linda Bacote",
      profilePic: "/images/instructor-6.jpg",
      profilePicBig: "/images/About/instructor-6.jpg",
      degination: "Digital Marketer",
      email: "Linda@example.com",
      phone: "570-543-3889",
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    },
    rating: 4.6,
    totalReviw: 10,
    mainthumbnail: "/images/course-09.jpg",
    videoThumbail: "/images/videoThumb/banner-course.jpg",
    duration: { hour: 15, min: 24, sec: 21 },
    entrolled: 250,
    lecture: 20,
    skill: "Advanced",
    language: "English",
    quiz: 10,
    certificate: "Yes",
    passParcentage: 90,
    deadline: "24 Dec, 2022",
    category: "Marketing",
    price: 39,
  },
];

export const comments = [
  {
    clientName: "Geraldine D. Anspach",
    clientdegi: "SEO Expert",
    clientcomment:
      "It is distracted by the readable content of page when looking at its layout. The point of using Ipsum is that it normal make for distribution of letters, as opposed to using content here it look like readable English Gravida orci vitae at aliquam.",
    clientPP: "/images/client-01.png",
  },
  {
    clientName: "Lorraine D. Raines",
    clientdegi: "WordPress Expert",
    clientcomment:
      "It is distracted by the readable content of page when looking at its layout. The point of using Ipsum is that it normal make for distribution of letters, as opposed to using content here it look like readable English Gravida orci vitae at aliquam.",
    clientPP: "/images/client-02.png",
  },
  {
    clientName: "David M. Bard",
    clientdegi: "JavaScript Developer",
    clientcomment:
      "It is distracted by the readable content of page when looking at its layout. The point of using Ipsum is that it normal make for distribution of letters, as opposed to using content here it look like readable English Gravida orci vitae at aliquam.",
    clientPP: "/images/client-03.png",
  },
];
export const Instructors = [
  {
    name: "James Carlson",
    profilePic: "/images/instructor-1 (1).jpg",
    degination: "SEO Expert",
    email: "James@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
  },
  {
    name: "Nancy Phipps",
    profilePic: "/images/instructor-2 (1).jpg",
    degination: "Digital Marketer",
    email: "Nancy@example.com",
    phone: "806-740-0589",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
  },
  {
    name: "Linda Bacote",
    profilePic: "/images/instructor-3.jpg",
    degination: "PHP Expert",
    email: "Linda@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
  },
  {
    name: "Alice McCoy",
    profilePic: "/images/instructor-4.jpg",
    degination: "UI Designer",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
  },
];

export const featureClass = [
  {
    title: "Flexible Classes",
    desc: "Fusce tempor, tortor vehicula posuere, mi est iaculis quam, nec luctus enim",
    icon: GiArchiveResearch,
  },
  {
    title: "Offline Mode",
    desc: "Fusce tempor, tortor vehicula posuere, mi est iaculis quam, nec luctus enim",
    icon: GiAlarmClock,
  },
  {
    title: "Flexible Learning",
    desc: "Fusce tempor, tortor vehicula posuere, mi est iaculis quam, nec luctus enim",
    icon: GiLaptop,
  },
  {
    title: "Educator Support",
    desc: "Fusce tempor, tortor vehicula posuere, mi est iaculis quam, nec luctus enim",
    icon: GiPoolTriangle,
  },
];

export const Blogs = [
  {
    id: 1,
    title: "Introduction to Javascript for the Beginners",
    category: "Business",
    date: "06 Nov, 2022",
    thumb: "/images/Blog/post-01.jpg",
    author: "John Kite Hazel Thomas",
  },
  { 
    id: 2,
    title: "Identity Design for a New Courses Crusader Work",
    category: "Education",
    date: "10 Nov, 2022",
    thumb: "/images/Blog/post-02.jpg",
    author: "Hazel Thomas",
  },
  {
    id: 3,
    title: "Grow Your Students Base With Free Courses",
    category: "Web Development",
    date: "12 Nov, 2022",
    thumb: "/images/Blog/post-03.jpg",
    author: " Joyce Knight",
  },
  {
    id: 4,
    title: "Easily Create Modify & Sell Courses Online",
    category: "Marketing",
    date: "15 Nov, 2022",
    thumb: "/images/Blog/post-04.jpg",
    author: "Hazel Thomas",
  },
];
export const Service2 = [
  {
    title: "Remote Learning",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    icon: "/images/About/feature-image-01.png",
  },
  {
    title: "Awesome Tutors",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    icon: "/images/About/feature-image-02.png",
  },
  {
    title: "Global Certificate",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    icon: "/images/About/feature-image-03.png",
  },
  {
    title: "Carrier Guideline",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    icon: "/images/About/feature-image-04.png",
  },
];
export const AllInstructor = [
  {
    name: "James Carlson",
    profilePic: "/images/About/instructor-1.jpg",
    degination: "SEO Expert",
    email: "James@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 70,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Nancy Phipps",
    profilePic: "/images/About/instructor-2.jpg",
    degination: "Digital Marketer",
    email: "Nancy@example.com",
    phone: "806-740-0589",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 70,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Troy Hall",
    profilePic: "/images/About/instructor-3.jpg",
    degination: "Digital Marketer",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Isabelle Bruner",
    profilePic: "/images/About/instructor-4.jpg",
    degination: "WordPress Expert",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Douglas Lage",
    profilePic: "/images/About/instructor-5.jpg",
    degination: "Laravel Expert",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Linda Bacote",
    profilePic: "/images/About/instructor-6.jpg",
    degination: "PHP Expert",
    email: "Linda@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "John Moss",
    profilePic: "/images/About/instructor-7.jpg",
    degination: "Digital Marketer",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
  {
    name: "Alice McCoy",
    profilePic: "/images/About/instructor-8.jpg",
    degination: "UI Designer",
    email: "Alice@example.com",
    phone: "570-543-3889",
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley..",
    skills: {
      firstSkill: "WordPress Development",
      firstProgress: 95,
      secondSkill: "Shopify Development",
      secondProgress: 90,
      thirdSkill: "Laravel Development",
      thirdProgress: 80,
      fourthSkill: "Live Support",
      fourthProgress: 80,
    },
    totalrating: 15,
    averageRaing: 4.7,
  },
];

export const AboutComment = [
  {
    name: "Emily G. Harper",
    degi: "Digital Marketer",
    comment:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla amet adipiscing sem neque.",
    star: 4.6,
    img: "/images/About/client-07.png",
  },

  {
    name: "Tina K. Leflore",
    degi: "SEO Expert",
    comment:
      "There are many variations of passages of Lorem Ipsum available, but the majority on have suffered alteration in some form, by a injected humour, or randomised.",
    star: 4.6,
    img: "/images/About/client-01.png",
  },
  {
    name: "David M. Bard",
    degi: "Content Writer",
    comment:
      "Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet dictum felis eu pede mollis pretium.",
    star: 4.6,
    img: "/images/About/client-03.png",
  },
  {
    name: "Jeffery C. Meyer",
    degi: "WordPress Expert",
    comment:
      "Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget fringilla mauris.",
    star: 4.6,
    img: "/images/About/client-05.png",
  },
  {
    name: "Robert E. Carter",
    degi: "SEO Expert",
    comment:
      "Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat tellus ullamcorper ultricies.",
    star: 4.6,
    img: "/images/About/client-02.png",
  },
  {
    name: "Kevin G. Curry",
    degi: "Web Developer",
    comment:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis par.",
    star: 4.6,
    img: "/images/About/client-06.png",
  },
  {
    name: "Julia H. Smith",
    degi: "Shopify Expert",
    comment:
      "Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapib lorem ante.",
    star: 4.6,
    img: "/images/About/client-04.png",
  },
];
